create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  id bigint primary key generated by default as identity,
  site_name text not null,
  footer_text text not null,
  city text not null default '',
  telegram_url text not null default '',
  whatsapp_url text not null default '',
  email text not null default '',
  phone text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.hero_content (
  id bigint primary key generated by default as identity,
  eyebrow text not null default '',
  title text not null,
  subtitle text not null default '',
  primary_button_text text not null default '',
  primary_button_url text not null default '',
  secondary_button_text text not null default '',
  secondary_button_url text not null default '',
  quote_text text not null default '',
  quote_author text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.sections (
  id bigint primary key generated by default as identity,
  key text unique not null,
  tag text not null default '',
  title text not null,
  description text not null default '',
  type text not null default 'cards',
  sort_order int not null default 1,
  is_published boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.section_items (
  id bigint primary key generated by default as identity,
  section_id bigint not null references public.sections(id) on delete cascade,
  title text not null,
  subtitle text not null default '',
  text text not null default '',
  value text not null default '',
  label text not null default '',
  image_url text not null default '',
  sort_order int not null default 1,
  is_published boolean not null default true
);

create table if not exists public.results (
  id bigint primary key generated by default as identity,
  student_name text not null,
  exam_type text not null,
  score text not null,
  short_text text not null default '',
  duration text not null default '',
  note text not null default '',
  sort_order int not null default 1,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.testimonials (
  id bigint primary key generated by default as identity,
  author_name text not null,
  author_role text not null default '',
  text text not null,
  stars int not null default 5,
  avatar_url text not null default '',
  sort_order int not null default 1,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.faq (
  id bigint primary key generated by default as identity,
  question text not null,
  answer text not null,
  category text not null default '',
  sort_order int not null default 1,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.seo_settings (
  id bigint primary key generated by default as identity,
  page_key text unique not null,
  meta_title text not null,
  meta_description text not null,
  og_title text not null default '',
  og_description text not null default '',
  og_image_url text not null default '',
  canonical_url text not null default '',
  favicon_url text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint primary key generated by default as identity,
  name text not null,
  contact text not null,
  student_grade text not null default '',
  goal text not null default '',
  message text not null default '',
  status text not null default 'new' check (status in ('new', 'contacted', 'in_progress', 'closed')),
  created_at timestamptz not null default now()
);

alter table public.site_settings enable row level security;
alter table public.hero_content enable row level security;
alter table public.sections enable row level security;
alter table public.section_items enable row level security;
alter table public.results enable row level security;
alter table public.testimonials enable row level security;
alter table public.faq enable row level security;
alter table public.seo_settings enable row level security;
alter table public.leads enable row level security;

create policy if not exists "Public read site_settings" on public.site_settings for select using (true);
create policy if not exists "Public read hero_content" on public.hero_content for select using (true);
create policy if not exists "Public read sections" on public.sections for select using (is_published = true);
create policy if not exists "Public read section_items" on public.section_items for select using (is_published = true);
create policy if not exists "Public read results" on public.results for select using (is_published = true);
create policy if not exists "Public read testimonials" on public.testimonials for select using (is_published = true);
create policy if not exists "Public read faq" on public.faq for select using (is_published = true);
create policy if not exists "Public read seo" on public.seo_settings for select using (true);
create policy if not exists "Public insert leads" on public.leads for insert with check (true);

create policy if not exists "Admin all site_settings" on public.site_settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy if not exists "Admin all hero_content" on public.hero_content for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy if not exists "Admin all sections" on public.sections for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy if not exists "Admin all section_items" on public.section_items for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy if not exists "Admin all results" on public.results for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy if not exists "Admin all testimonials" on public.testimonials for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy if not exists "Admin all faq" on public.faq for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy if not exists "Admin all seo" on public.seo_settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy if not exists "Admin all leads" on public.leads for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
